import cv2 as cv

image = cv.imread('img 3.png')

hsv_image = cv.cvtColor(image, cv.COLOR_BGR2HSV)

lower_yellow = (5, 0, 0)
upper_yellow = (50, 255, 255)

# Create a mask to isolate yellow regions in the image
yellow_mask = cv.inRange(hsv_image, lower_yellow, upper_yellow)

# Extract the yellow channel by bitwise ANDing the original image with the mask
yellow_channel = cv.bitwise_and(image, image, mask=yellow_mask)

# Save or display the yellow channel image
cv.imwrite('processed/img 3.png', yellow_channel)